### ISSUE TITLE
Crazyhouse Chess for Windows

### ISSUE THREAD

**Issue by ChessGUI** [ekjellman/crazyhouse#1]
Ferdinand http://www.talkchess.com/forum/profile.php?mode=viewprofile&u=4054 wants to compile a Windows binary of your source code. Please join CCC forum for free and contact him directly.

Is Crazyhouse WinBoard or UCI compatible and can it be embedded into external interfaces like
WinBoard http://www.open-aurec.com/wbforum/viewtopic.php?f=19&t=51528 etc.?

WB-1 ~ http://home.hccnet.nl/h.g.muller/engine-intf.html
WB-2 ~ http://hgm.nubati.net/CECP.html
UCI ~ http://download.shredderchess.com/div/uci.zip

**Comment by ekjellman** [comment]
Greetings,

If you find use for this code go ahead and do what you'd like with it, but it's completely abandonware right now. It isn't functional in any way, it was a pair programming experiment I was starting with someone and it was abandoned.

No, it does not support WinBoard or UCI. It doesn't work at all. ^_^;

Good luck with your project!
